del /s /q *.o 
del /s /q *.__i
del /s /q *.crf 
del /s /q *.d
del /s /q *.lst 
del /s /q *.map 
del /s /q *.axf 
del /s /q *.htm 
del /s /q *.sct 
del /s /q *.lnp 
del /s /q *.tra 
del /s /q *.plg 
del /s /q *.bak 
del /s /q *.htm 
del /s /q *._ia 
del /s /q *.iex
del /s /q *.plg
del /s /q *.uvgui.* 
del /s /q *.dep
